/* This file is generated by scripts/generate_openapi_types.py. Do not edit manually. */

export type ApiGroup = "admissions" | "approvals" | "auth" | "benchmarks" | "candidates" | "evaluations" | "experience" | "ledger" | "query-shapes" | "rollbacks" | "runs" | "settings" | "system" | "targets" | "telemetry" | "workloads";
export type ApiPath = "/api/v1/admissions" | "/api/v1/approvals" | "/api/v1/auth" | "/api/v1/benchmarks" | "/api/v1/candidates" | "/api/v1/evaluations" | "/api/v1/experience" | "/api/v1/ledger" | "/api/v1/query-shapes" | "/api/v1/rollbacks" | "/api/v1/runs" | "/api/v1/settings" | "/api/v1/system" | "/api/v1/targets" | "/api/v1/telemetry" | "/api/v1/workloads";

export interface ApiGroupResponse {
  group: ApiGroup;
  status: "not_configured";
  records: readonly never[];
}

export type ApiGetResponses = {
  [Path in ApiPath]: ApiGroupResponse;
};
