#!/usr/bin/env python3
"""Generate the small frontend OpenAPI type surface without a host Node dependency."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
OUTPUT = ROOT / "frontend/src/api/openapi.generated.ts"
sys.path.insert(0, str(BACKEND))

from app.main import app  # noqa: E402


def render() -> str:
    """Render stable TypeScript paths and the documented group response."""
    paths = tuple(sorted(path for path in app.openapi()["paths"] if path.startswith("/api/v1/")))
    groups = tuple(path.rsplit("/", 1)[1] for path in paths)
    group_union = " | ".join(f'"{group}"' for group in groups)
    path_union = " | ".join(f'"{path}"' for path in paths)
    return "\n".join(
        (
            "/* This file is generated by scripts/generate_openapi_types.py. Do not edit manually. */",
            "",
            f"export type ApiGroup = {group_union};",
            f"export type ApiPath = {path_union};",
            "",
            "export interface ApiGroupResponse {",
            "  group: ApiGroup;",
            "  records: readonly Record<string, unknown>[];",
            "  limit: number;",
            "  offset: number;",
            "}",
            "",
            "export type ApiGetResponses = {",
            "  [Path in ApiPath]: ApiGroupResponse;",
            "};",
            "",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated types are stale")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"Generated OpenAPI types are stale: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"Generated OpenAPI types are current: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated)
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
